import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Noise from "@/components/Noise";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        <Noise />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
